# Generated by Django 5.1.6 on 2025-02-21 05:16

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mafazapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
