# Generated by Django 5.1.6 on 2025-02-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafazapp', '0003_passwordresetrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_requested',
            field=models.BooleanField(default=False),
        ),
    ]
