# Generated by Django 5.1.6 on 2025-02-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafazapp', '0004_customuser_has_requested'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('total_investment', models.DecimalField(decimal_places=2, max_digits=15)),
                ('min_roi', models.DecimalField(decimal_places=2, help_text='Minimum Return on Investment (%)', max_digits=5)),
                ('max_roi', models.DecimalField(decimal_places=2, help_text='Maximum Return on Investment (%)', max_digits=5)),
                ('project_description', models.TextField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='project_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
