# Generated by Django 5.1.6 on 2025-02-21 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafazapp', '0005_investmentproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('investment', 'Investment'), ('withdrawal', 'Withdrawal')], max_length=20)),
                ('narration', models.TextField()),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='receipts/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mafazapp.investmentproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
