# Generated by Django 5.1.6 on 2025-02-21 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafazapp', '0006_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roi', models.DecimalField(blank=True, decimal_places=2, help_text='Custom roi', max_digits=5, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_users', to='mafazapp.investmentproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
