# Generated by Django 5.1.6 on 2025-02-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafazapp', '0008_userdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='pending', max_length=10),
        ),
    ]
