# Generated by Django 5.1.6 on 2025-02-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafazapp', '0009_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprojectassignment',
            name='return_period',
            field=models.CharField(choices=[('5m', '5 Minutes'), ('10m', '10 Minutes'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semiannual', 'Semiannual'), ('annual', 'Annual')], default='annual', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprojectassignment',
            name='roi',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custom ROI', max_digits=5, null=True),
        ),
    ]
