# Generated by Django 5.1.6 on 2025-02-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafazapp', '0010_userprojectassignment_return_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprojectassignment',
            name='return_period',
            field=models.CharField(choices=[('5m', '5 Minutes'), ('10m', '10 Minutes'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semiannual', 'Semiannual'), ('annual', 'Annual')], default='5m', max_length=20),
        ),
    ]
