# Generated by Django 5.1.6 on 2025-03-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafazapp', '0012_alter_transaction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentproject',
            name='images',
        ),
        migrations.AddField(
            model_name='investmentproject',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
        migrations.AddField(
            model_name='investmentproject',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
        migrations.AddField(
            model_name='investmentproject',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='project_images/'),
        ),
        migrations.AddField(
            model_name='investmentproject',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
